{% set version = "1.5.0" %}
{% set org = "cyclus" %}
{% set branch = "master" %}
{% set sha256 = "1feee832b0c7284c0e1dce11c58da109f9d3955b2f8b38ce3090ce08ef2fc2c1" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cyclus/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or not (py27 or py35)]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - python
    - cython
    - pandas
    - cmake
    - pkg-config
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
    - jinja2
    - numpy x.x
  run:
    - python
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
    - numpy x.x
    - pandas

test:
  requires:
    - setuptools
    - nose
    - pytables

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - BaaaaaM
