{% set version = "dev" %}

package:
  name: cyclus
  version: {{ version }}

source:
  git_url: https://github.com/cyclus/cyclus.git
  git_rev: main

build:
  number: 2
  skip: true  # [win or osx]
  detect_binary_files_with_prefix: true
  preserve_egg_dir: true
    
requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - pandas
    - jinja2
    # C/C++ libraries
    - blis
    - bzip2
    - coin-or-cbc
    - coin-or-cgl
    - coin-or-clp
    - coin-or-osi
    - coin-or-utils
    - glib
    - glibmm
    - hdf5
    - icu
    - libaec
    - libboost-devel
    - libcurl
    - libiconv
    - liblapack
    - libxmlpp-4.0
    - libxml2
    - openssl
    - sigcpp-3.0
    - sqlite
    - zlib
  run:
    - python
    - blis
    - pandas


test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pytest
    - pytables
  source_files:
    - tests
    - share/dbtypes.json
    - src/hdf5_back_gen.py

about:
  home: http://fuelcycle.org/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - gonuke
    - katyhuff
    - FlanFlanagan
    - bennibbelink
    - munkm
    - abachma2
