{% set version = "1.4.0" %}
{% set org = "cyclus" %}
{% set branch = "master" %}
{% set sha256 = "9b4cb57a1c67329d7b312bd038893de4e82ade2e822ba33a3b2ff7c14beca7da" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/{{ org }}/cyclus/archive/{{ branch }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win or not py35]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - python
    - cmake
    - pkg-config
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.18|0.2.18.*
    - boost 1.61.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
  run:
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.18|0.2.18.*
    - boost 1.61.*
    - hdf5 1.8.17|1.8.17.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*

test:
  requires:
    - setuptools
    - nose
    - pytables

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - BaaaaaM
