{% set version = "1.6.0" %}

package:
  name: cyclus
  version: {{ version }}

source:
  git_url: https://github.com/cyclus/cyclus.git
  git_rev: 1.6.0

build:
  number: 3
  skip: True  # [win or osx or py<=27]
  detect_binary_files_with_prefix: true
  preserve_egg_dir: True
    
requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - coincbc
    - libboost-devel
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - jinja2
    - cython
    - pip
    - setuptools
  host:
    - coincbc
    - libboost-devel
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - blis
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - python
    - pprintpp
    - cython
  run:
    - coincbc
    - libboost-devel
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - blis
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - python
    - pprintpp

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pytest
    - pytables
  source_files:
    - tests
    - share/dbtypes.json
    - src/hdf5_back_gen.py

about:
  home: http://fuelcycle.org/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
    - stompsjo
    - bennibbelink
