{% set version = "1.5.4" %}
{% set sha256 = "57b4b68d81852d4c7350d3788cfeaf6093cb9cdf8dd524fe10ad33581f55e043" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cyclus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py27 or py34 or (osx and py35)]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pandas
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas
    - boost-cpp
    - hdf5
    - sqlite
    - pcre
    - gettext
    - bzip2
    - xz
    - jinja2
    - numpy
  run:
    - python
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas
    - boost-cpp
    - hdf5
    - sqlite
    - pcre
    - gettext
    - bzip2
    - xz
    - {{ pin_compatible('numpy') }}
    - pandas
    - websockets
    - pprintpp

test:
  requires:
    - setuptools
    - nose
    - pytables
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
