{% set version = "1.5.3" %}
{% set sha256 = "9371c460d446a07cf3b4deef2fd16319e575eba19d7fdee03f056a3fa217dd09" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cyclus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4 
  skip: True  # [win]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cyclus-build-deps
  run:
    - cyclus-build-deps

test:
  requires:
    - setuptools
    - nose
    - pytables
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
