{% set version = "1.5.2" %}
{% set sha256 = "633b02182f1655135086839a549f6228953fa2b8c0fdf0fe337206798ec35c01" %}
{% set variant = "openblas" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cyclus/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py34]
  detect_binary_files_with_prefix: true
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - python
    - cython
    - pandas
    - cmake
    - pkg-config
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - boost-cpp 1.65.1
    - hdf5 1.8.18|1.8.18.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
    - jinja2
    - numpy 1.11.*
  run:
    - python
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - boost-cpp 1.65.1
    - hdf5 1.8.18|1.8.18.*
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
    - numpy >=1.11
    - pandas

test:
  requires:
    - setuptools
    - nose
    - pytables
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
