appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MgJhsDquhYl3LK1BfGv03T8N2qqyknO0FcftPKImLnuuX0CD29hpRuhes73iK5OokysfegncbIHz1XKOgBtdLWYA5MY5r9JMdtK3s31tTk40sdDarDZ06jSKZc6TyqEor8A/sJ8iCLMTJbBnws3xBRwbK1cKKYsHNKUe2kz1t85RhClMSeFTXUzykLVTeS1sdyHxotWaMw1Uilk/LLJplpPVS/CGfj2h7jg1PSuYMrJ4UpIXhHRySIjmNKz4Hl5mvc70Iy6qGtI0lqV8+asQmPZQUdi5MdgduzS21xUZmkPcm6yXPf2M4osI6oNFijjdVUFbtcTkG68tdjvjfbdB28FNGTVIwSckUJrvK79cfF50spbhJ4rl3dtIkZawQ19xPB8qBOPzR73pier34d/NrEr01Qtqx7Bnc0zlgTPEMa5m5oeHNToIy2xEYXaV+jJtw/gEsp2OW32/lN5gzMvQvBvL8jhfpsII72igzUR77T2xeE3I1jCbuMVTVeQD5be7HA6jpAFElIvrChyTCZiPj+y7BlUzJbOwor34AECYaxVcZqnJhvDgxFPMik+O2wklahZWcwgzypSvGBqPlnUZfa6OuazF7GV33xIM3NzpFA6iotiuqU/YK1Jy0+hZXCRGTq402/4ErAR0f+rySUMBH3F5cpxLYFVzCyrY8Vg3WTQ=}
